version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: pesca-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: diego
      MONGO_INITDB_ROOT_PASSWORD: pescacria

volumes:
  mongodbdata:
